export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="${ZSH_THEME:-clean}"

plugins=(
  git
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# Modular config
source ~/.zsh/keybindings.zsh
source ~/.zsh/history.zsh
source ~/.zsh/fzf.zsh
source ~/.zsh/plugins.zsh

# Optional NVM
[ -f ~/.zsh/nvm.zsh ] && source ~/.zsh/nvm.zsh

# Optional local overrides (not committed)
[ -f ~/.zshrc.local ] && source ~/.zshrc.local

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# bun completions
[ -s "/home/jose/.bun/_bun" ] && source "/home/jose/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
source ~/perl5/perlbrew/etc/bashrc

export TERM=xterm-256color


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/jose/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/jose/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/jose/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/jose/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

export PATH="$HOME/.emacs.d/bin:$PATH"

